name: feature push
on:
  push:
    branches:
      - feature/*
      - main

jobs:
  update_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug
        run: |
          echo ${{ github.event_name }}
          echo "event name is:" ${{ github.event_name }}
          echo ${{ github.ref }}
          echo ${{ github.event.pull_request.head.ref }}
          echo ${{ github.event.pull_request.base.ref }}